/*
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/T-Systems-MMS/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */

import { ValidatorFn, Validators } from '@angular/forms';
import { BaseFormControlFactory } from 'openapi-typescript-angular-generator';

import { MovieGenre } from './movieGenre';


export interface Movie { 
    movieId: string;
    title: string;
    movieGenres?: Array<MovieGenre>;
}

/**
 * Namespace for property- and property-value-enumerations of Movie.
 */
export namespace Movie {
    /**
     * All properties of Movie.
     */
    export enum Properties {
        movieId = 'movieId',
        title = 'title',
        movieGenres = 'movieGenres'
    }

    /**
    * A map of tuples with error name and `ValidatorFn` for each property of Movie.
    */
    export const ModelValidators: {[K in keyof Movie]: [string, ValidatorFn][]} = {
        movieId: [
                ['required', Validators.required],
                ['minlength', Validators.minLength(1)],
        ],
        title: [
                ['required', Validators.required],
                ['minlength', Validators.minLength(1)],
        ],
        movieGenres: [
        ],
    };

    /**
    * The FormControlFactory for Movie.
    */
    export class FormControlFactory extends BaseFormControlFactory<Movie> {

        /**
         * Constructor.
         *
         * @param model An existing model for Movie.
         *              If given, all form-controls of the factory automatically have the value of this model. If this
         *              model is not given, all values are `null`.
         */
        constructor(
          model: Movie = {
            movieId: null,
            title: null,
            movieGenres: null,
          }
        ) {
            super(model, Movie.ModelValidators);
        }
    }

}


